### ISSUE TITLE
Wrong  suggestions awaiting approval count

### ISSUE THREAD

**Issue by Suvitruf** [g3rv4/Traducir#109]
https://ru.traducir.win/

It shows 6 suggestions:

> ![traducir win - soru - mozilla firefox 2019-02-10 13 47 23](https://user-images.githubusercontent.com/1946939/52532715-76714a80-2d3a-11e9-9117-a53da3508bcd.png)

But when I click it, it shows 8 in results:

> ![traducir win - soru - mozilla firefox 2019-02-10 13 47 32](https://user-images.githubusercontent.com/1946939/52532716-76714a80-2d3a-11e9-9d60-6202588559cf.png)

**Comment by g3rv4** [comment]
Hi there!

When this happens, have you tried refreshing the page?

If refreshing fixes it, then that’s a known issue: if while you’re on the site somebody else adds a suggestion (or approves or rejects one) you won’t see the stats update.

Ideally, we’d have websockets to learn about that in real time. However, given that this site has really low traffic, I don’t think it’s totally worth it.

We could also poll every N seconds, but again... I’m not super convinced that it’s worth the effort.

If you were interested in implementing either of these, I’d be happy to review and merge a PR

**Comment by Suvitruf** [comment]
Hello, @g3rv4. 

Right now it shows correct number. But I'm pretty sure I've updated the page. If it's just cache problem, then nvm )
