### ISSUE TITLE
Inconsistent number of suggestions

### ISSUE THREAD

**Issue by Alexolut** [g3rv4/Traducir#116]
On the main page of https://ru.traducir.win/ I see the 4 strings awaiting approval:

![2019-05-21 07_28_57-traducir win - SOru](https://user-images.githubusercontent.com/12843204/58068633-ca41ca00-7b9a-11e9-8c1d-872a0fea0d7c.png)

After click on item the result is empty:

![2019-05-21 07_29_06-traducir win - SOru](https://user-images.githubusercontent.com/12843204/58068663-e34a7b00-7b9a-11e9-8b6c-577e9e399eb0.png)

**Comment by g3rv4** [comment]
If you refresh, does it get fixed? if that’s the case, then it’s the same thing as #109

we’d need to open a websocket connection to be notified about changes other people make to the system to keep it updated. That’s not something on the plans.
