### ISSUE TITLE
Feature request: mark as important as well as suggest translation on the same shot

### ISSUE THREAD

**Issue by fedorqui** [g3rv4/Traducir#118]
Quite often I find myself translating strings that I have found in English in the SO en español. Since I found them in the site, it means they are visible to all users, so -to me- it is urgent to have them translated. So when I send the translation I normally pick the "mark as urgent" option, so that reviewers can check them faster.

Currently it is a bit long to translate + mark as urgent, since every action closes the modal. Would it be possible to have the modal not close when marking as urgent, so that translating + marking as urgent can be done without too many clicks?

**Comment by g3rv4** [comment]
I'll get this one done :)

**Comment by g3rv4** [comment]
It's alive!

**Comment by fedorqui** [comment]
So cool! Thanks a lot @g3rv4
