### ISSUE TITLE
Let users delete their own suggestions

### ISSUE THREAD

**Issue by g3rv4** [g3rv4/Traducir#12]
That :)

**Comment by topcatarg** [comment]
- Backend

Add a function to StringsController to allow deletion. Store on history (?). 

- Frontend

Add a button to the user only if the suggestion if from himself (herself).

**Comment by g3rv4** [comment]
yup, that's basically it... we should make sure we create the corresponding `StringSuggestionHistory`. We already have a [`StringSuggestionHistoryTypeId`](https://github.com/g3rv4/Traducir/blob/master/Traducir.Core/Models/Enums/StringSuggestionHistoryType.cs) (I thought about it when dealing with the data model but never got to it)
