### ISSUE TITLE
ru.traducir gives 502 error

### ISSUE THREAD

**Issue by Suvitruf** [g3rv4/Traducir#133]
https://ru.traducir.win

![ru traducir win _ 502_ Bad gateway - Mozilla Firefox 2019-12-31 15 20 41](https://user-images.githubusercontent.com/1946939/71621568-1ea53180-2be1-11ea-970f-f4b633db0612.png)

**Comment by g3rv4** [comment]
Thanks for the report! yup, I've changed the server it runs on and I'm chasing down a high CPU issue.

It's back up now... I'm going to be at [The terminal](https://chat.stackexchange.com/rooms/84778/the-terminal)
