### ISSUE TITLE
Test pathological regexes

### ISSUE THREAD

**Issue by g3rv4** [g3rv4/Traducir#16]
Regexes that are bad bad bad probably break the system. Get some from @Mariano-SOes and test them!

**Comment by g3rv4** [comment]
yeah, sorry... I edited the comment by the email had already triggered... I imagine using GitHub with a cool handle has its disadvantages ;)

**Comment by Mariano-SOes** [comment]
Ckecklist:

- [ ] analize [code](https://github.com/g3rv4/Traducir/blob/master/Traducir.Api/Controllers/StringsController.cs#L101-L126)
- [ ] Option Compiled?
- [ ] Explicit Capture
- [ ] Default to IgnoreCase and Singleline?
    Meaning a user should use `(?-i)` or `(?-s)` to turn it off
- [ ] Limit?
- [ ] Check culture info for `\w` & friends in Russian and Japanese
- [ ] Identify problematic strings in db
- [ ] Tests
    - Syntax errors
    - Unicode properties
    - Catastrophic backtracking
    - Evil variable length lookbehings
    - Regex-fu with balancing groups and conditionals

**Comment by g3rv4** [comment]
I don't think we'll ever do this. Closing it to avoid noise on the list of issues.

Also, Mariano: hi! <3
