### ISSUE TITLE
Add clarity on spaces

### ISSUE THREAD

**Issue by g3rv4** [g3rv4/Traducir#17]
Some strings have spaces on weird places... at the end, at the beggining. The current implementation doesn't make it easy to review them, as mentioned in #14 

Give our reviewers the tool to do their jobs!

**Comment by Mariano-SOes** [comment]
Documenting what we talked on [our chat](https://chat.stackexchange.com/rooms/72224/conversation/traducir-win-raw-string).

---

**A. Default behaviour**

1. count leading whitespace in original string
2. count trailing whitespace in original string
3. add/remove leading whitespace to/from suggestion to match 1
4. add/remove trailing whitespace to/from suggestion to match 2

---

**B. New option (reviewers only)**

Checkbox: `[  ] Raw string`

when enabled on a new suggestion:

- it won't modify the whitespace (no trimming and no adding)
- no other validation is done
    - it won't check if all variables are used <sup>* no issue yet, needs reference</sup>

**Comment by carlosmunozrodriguez** [comment]
I will take this one

**Comment by g3rv4** [comment]
@carlosmunozrodriguez are you working on this one? asking only because we didn't hear back and somebody else may want to pick it.

Thanks!

**Comment by g3rv4** [comment]
@Mariano-SOes what does _no issue yet, needs reference_ refer to?

**Comment by Mariano-SOes** [comment]
Referenced now in #38
