### ISSUE TITLE
Refresh list and remember scroll position when Suggestion is submitted

### ISSUE THREAD

**Issue by Pikoh** [g3rv4/Traducir#19]
When you submit a suggestion, if you have a filter (let's say, "Strings without suggestions")  it would be nice that when you go back to the list, this would be refreshed so the string you just suggested translation won't appear anymore without having to click on "Reset".

It would also be useful that when you go back from the "submit suggestion" page, the application remembers the scroll position in the list. Let's say that you start translating in the middle of a list of e.g. 1500 sentences. It's a pain after submitting a sugestion to manually scroll again to the point where you were before.

**Comment by g3rv4** [comment]
This is actually a big issue... especially when doing translations in bulk.

**Comment by g3rv4** [comment]
I fixed this with a modal... I started disliking the solution a lot, I ended disliking the solution a little.
