### ISSUE TITLE
Unicode characters break on the usernames

### ISSUE THREAD

**Issue by g3rv4** [g3rv4/Traducir#22]
Which... is kind of embarrassing

**Comment by g3rv4** [comment]
[As mentioned by Mariano](https://chat.stackexchange.com/transcript/message/43942812#43942812) the issue is with the html entities returned by the SO's API

**Comment by g3rv4** [comment]
As discussed on chat, let's change the filter and roll this back

**Comment by g3rv4** [comment]
@carlosmunozrodriguez would you mind checking that this is actually fixed? just log in into the system and verify that your name appears ok on a suggestion you make

**Comment by carlosmunozrodriguez** [comment]
Verified, the user name appears correctly in the top banner and in a suggestion
