### ISSUE TITLE
Keep deleted strings for some time

### ISSUE THREAD

**Issue by Mariano-SOes** [g3rv4/Traducir#31]
SO constantly removes strings from Tx. That implies that sometimes a user can't find a string or a suggestion, making it harder to understand what's going on or what's the string he's looking for.

Proposal: despite its `DeletionDate`, keep the string for some time:

- searchable
- reviewable

Suggested time frame: 5 days.

**Comment by g3rv4** [comment]
these strings appear on the system but will fail when being pushed (because transifex doesn't know them). If/when SO adds them back, the push will succeed
