### ISSUE TITLE
The links in the suggestions list point to the same user

### ISSUE THREAD

**Issue by BlasFerna** [g3rv4/Traducir#35]
I know this may not be very important, but by testing I found that the links point to the same SOes user.

![img](https://user-images.githubusercontent.com/8385910/38818507-65000084-4168-11e8-939c-548f80525422.PNG)

**Comment by g3rv4** [comment]
nice catch!

**Comment by g3rv4** [comment]
This should be fixed and in prod now. Thanks for the report!
