### ISSUE TITLE
Filter for "My Suggestions"

### ISSUE THREAD

**Issue by Pikoh** [g3rv4/Traducir#78]
Issue [#68](https://github.com/g3rv4/Traducir/issues/68) gave us a nice way to know what had happened with our suggestions. But it would be nice to have a way to filter them, mainly by its state (Approved, rejected...),specially if you have a lot of suggestions (as myself) :)

**Comment by g3rv4** [comment]
[ ] Filter by state only
[ ] Ensure that the url gets updated (so that urls are shareable)
[ ] Add filter on the database to speed up queries
