### ISSUE TITLE
Help! (I mean what about the docs for end-users)

### ISSUE THREAD

**Issue by rubenrivera** [g3rv4/Traducir#89]
Thanks to Pikoh I recently learned about the use of "Mark as urgent" but knowing me it's very like that I will forget what I learned (shame on me).

It's it OK to make a PR to add a Help section to the readme.md for non-so-pretty-obvious things?

**Comment by g3rv4** [comment]
absolutely!

**Comment by rubenrivera** [comment]
Sent #90
